- name: Check if oh-my-fish is installed
  stat:
    path: '/etc/omf.installed'
  register: omf

- name: Update repositories cache
  apt:
    update_cache: yes
  when: not omf.stat.exists
    
- name: Ensure git is present
  become: yes
  package: name=git state=present
  when: not omf.stat.exists

- name: Create omf tmp directory
  file:
    path: /tmp/omf
    state: directory
  when: not omf.stat.exists

- name: Download omf install file
  get_url:
    url: https://get.oh-my.fish
    dest: /tmp/omf/install_omf.fish
    mode: u+rwx
    checksum: sha256:{{ fish_checksum }}
  when: not omf.stat.exists

- name: Determine shell executable location
  command: which fish
  register: fish
  when: not omf.stat.exists

- name: Install oh-my-fish
  shell: 
    cmd: fish /tmp/omf/install_omf.fish --path=~/.local/share/omf --config=~/.config/omf --noninteractive
  when: not omf.stat.exists

- name: Mark oh-my-fish installed with /etc/omf.installed
  become: yes
  become_method: sudo
  file:
    path: /etc/omf.installed
    state: touch
  when: not omf.stat.exists

- name: Install OMF packages
  shell: 
    cmd: "omf install {{item | quote}}"
    executable: '{{fish.stdout}}'
  with_items: '{{fish_plugins}}'
  when: not omf.stat.exists
    

