- name: Check if oh-my-fish is installed
  stat:
    path: '/etc/omf.installed'
  register: omf

- name: Clone oh-my-fish repo
  git:
    repo: 'https://github.com/oh-my-fish/oh-my-fish'
    dest: '/tmp/omf'
    clone: yes
  when: not omf.stat.exists

- name: Install oh-my-fish
  become: true
  command: /tmp/omf/bin/install -y --offline --noninteractive
  when: not omf.stat.exists

- name: Mark oh-my-fish installed with /etc/omf.installed
  become: true
  become_method: sudo
  file:
    path: /etc/omf.installed
    state: touch

- name: Determine shell executable location
  command: which fish
  register: fish

- name: Install OMF packages
  become: true
  shell: "omf install {{item}}"
  with_items: '{{fish_plugins}}'
  args:
    executable: '{{fish.stdout}}'

