# Install
- name: package | fish
  package: name="{{ fish_name }}" state="{{ install_state }}"
  tags:
    - bootstrap
    - bootstrap_fish
    - install
    - install_fish
  become: yes

- name: configure | change default shell
  user: name="{{ user_name }}" shell="/usr/local/bin/fish"
  become: yes


- name: Change user shell to fish 
  vars:
    the_user: "{{ ansible_user_id }}"
  become: yes
  user:
    name: "{{ the_user }}"
    shell: "{{ fish.stdout }}"