# tasks file for pycharm
---
- name: create (download) directory
  become: yes
  file:
    path: "{{ pycharm_downloads_path }}"
    state: directory
    mode: 0755
  tags:
    - configuration
    - pycharm
    - pycharm-download

- name: download
  become: yes
  get_url:
    url: "{{ pycharm_download_url }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    mode: 0644
  tags:
    - configuration
    - pycharm
    - pycharm-download

- block:

  - name: install | old
    become: yes
    unarchive:
      src: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
      dest: "{{ pycharm_install_prefix }}"
      creates: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_version }}"
      copy: false
    when: pycharm_version is version('2016.1.0', '<')
    tags:
      - pycharm-install-old

  - name: install | new
    become: yes
    unarchive:
      src: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
      dest: "{{ pycharm_install_prefix }}"
      creates: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}"
      copy: false
    when: pycharm_version is version('2016.1.0', '>=')
    tags:
      - pycharm-install-new

  tags:
    - configuration
    - pycharm
    - pycharm-install
