# TODO: Develop role for OS X
# - import_tasks: mac.yml
#   when: ansible_os_family == "Darwin"

- import_tasks: ubuntu.yml
  vars:
    visual_studio_code_extensions:
      - levkoivanchuk.vscode-essentials
  when: ansible_os_family == "Debian"
