- name: Install recommended dependencies for pyenv
  homebrew:
    name:
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib
    state: present

- name: Install python
  homebrew: name=python state=present

- name: Install pyenv
  homebrew: name=pyenv state=present
  tags: pyenv

- name: Install pyenv-virtualenv
  homebrew: name=pyenv-virtualenv state=present
  tags: pyenv

- name: Install Python versions with pyenv
  shell: 'pyenv install {{item}} --skip-existing'
  args:
    creates: "{{ '~/.pyenv/versions/' + item | expanduser }}"
  with_items: '{{pyenv_global_versions}}'
  tags: pyenv

- name: Set global Python versions with pyenv
  copy:
    content: "system\n{% for version in pyenv_global_versions %}{{ version }}\n{% endfor %}"
    dest: "{{ '~/.pyenv/version' }}"
  tags: pyenv