
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"

- import_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Check if pytest.ini file exists
  stat: path="{{dotfiles_user_home}}/pytest.ini"
  register: pytest_stat

- name: Back up pytest.ini file
  command: mv ~/pytest.ini ~/pytest.ini.bak
  args:
    creates: "{{dotfiles_user_home}}/pytest.ini"
  when: pytest_stat.stat.exists

# - name: Link pytest.ini file
#   file:
#     src: "{{dotfiles_home}}/roles/python/files/pytest.ini"
#     dest: "{{dotfiles_user_home}}/pytest.ini"
#     state: link

# - name: Update pip
#   shell: pip install --upgrade pip

- name: Update pip3
  shell: pip3 install --upgrade pip
  when: ansible_distribution_major_version != "16"

- name: Install pipx
  tags: pipx
  shell: "python3 -m pip install pipx && python3 -m pipx ensurepath"
  args:
    creates: "{{dotfiles_user_home}}/.local/bin/pipx"
  ignore_errors: yes
  when: ansible_distribution_major_version != "16"

- name: Download poetry install file
  get_url:
    url: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
    dest: /tmp/get_poetry.py
    mode: u+rwx
    checksum: sha256:{{ python_poetry_install_checksum }}
  when: ansible_distribution_major_version != "16"

- name: Install poetry
  tags: poetry
  shell: "python3 /tmp/get_poetry.py"
  args:
    creates: "{{dotfiles_user_home}}/.poetry/bin/poetry"
  when: ansible_distribution_major_version != "16"

- name: Remove poetry install file
  file:
    path: /tmp/get_poetry.py
    state: absent
  when: ansible_distribution_major_version != "16"

# A global `virtualenv` command is needed for prezto's pyenv-virtualenv to work
- name: Install virtualenv
  shell: "python3 -m pip install virtualenv"
  args:
    creates: "/usr/local/bin/virtualenv"
  when: ansible_distribution_major_version != "16"

# - name: Load dist-packages to PYTHONPATH
#   blockinfile:
#     dest: "{{ pyenv_bashrc_path }}"
#     marker: "# {mark} ANSIBLE MANAGED BLOCK: PYTHONPATH"
#     block: |
#       export PYTHONPATH=/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages