- name: Update repositories cache
  become: yes
  apt:
    update_cache: yes

- name: Ensure dirmngr is present
  become: yes
  package: name=dirmngr state=present

- name: Add extra sources lists
  become: yes
  become_method: sudo 
  apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present

- name: Update repositories cache
  become: yes
  apt:
    update_cache: yes

- name: Install Python dependencies
  become: yes
  become_method: sudo
  ignore_errors: yes
  package: 
    name: "{{item}}" 
    state: present
  with_items:
    - python3
    - python3-pip
    # - python-pip
    # - python3.8
  when: ansible_distribution_major_version != "16"

- name: Install Python dependencies for Ubuntu 16.04
  become: yes
  become_method: sudo
  ignore_errors: yes
  package: 
    name: "{{item}}" 
    state: present
  with_items:
    - python
    - python-apt
    - python3
    - python3-apt
    - python3-pip
    # - python3.8
    # - python3.8-distutils
  when: ansible_distribution_major_version == "16"

# - name: Install Python dependencies for Ubuntu 16.04
#   become: yes
#   become_method: sudo
#   ignore_errors: yes
#   package: 
#     name: "{{item}}" 
#     state: absent
#   with_items:
#     - python3-pip
#   when: ansible_distribution_major_version == "16"

# - name: Set python3.8 as default for Ubuntu 16.04
#   alternatives:
#     name: python
#     link: /usr/bin/python
#     path: /usr/bin/python3.8
#   when: ansible_distribution_major_version == "16"

# - name: Set python3.8 as default for Ubuntu 16.04
#   alternatives:
#     name: python3
#     link: /usr/bin/python3
#     path: /usr/bin/python3.8
#   when: ansible_distribution_major_version == "16"

# - name: Download pip installer
#   get_url: 
#     url: https://bootstrap.pypa.io/get-pip.py 
#     dest: /tmp/get-pip.py
#   when: ansible_distribution_major_version == "16"

# - name: Install pip on Ubuntu 16.05
#   shell: python3 /tmp/get-pip.py
#   when: ansible_distribution_major_version == "16"

# - name: Remove the /tmp/get-pip.py
#   file: path=/tmp/get-pip.py state=absent

# - name: Install apt_pkg on Ubuntu 16.05
#   shell: cd /usr/lib/python/dist-packages && ln -s apt_pkg.cpython-35m-x86_64-linux-gnu.so apt_pkg.so
#   when: ansible_distribution_major_version == "16"

# - name: Install apt_pkg on Ubuntu 16.05
#   shell: cd /usr/lib/python3/dist-packages && ln -s apt_pkg.cpython-35m-x86_64-linux-gnu.so apt_pkg.so
#   when: ansible_distribution_major_version == "16"

# - name: Set python3.8 as default for Ubuntu 16.04
#   become: yes
#   become_method: sudo
#   shell: >-
#     update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1
#     update-alternatives --set python /usr/bin/python3.8

# - import_role: 
#     name: ./python/pyenv
#   vars:
#     pyenv_global: "{{ python_global_version }} system"
#     pyenv_python_versions: '{{pyenv_global_versions}}'