- name: Update repositories cache
  become: yes
  apt:
    update_cache: yes

- name: Install Python dependencies
  become: yes
  become_method: sudo
  ignore_errors: yes
  package: 
    name: "{{item}}" 
    state: present
  with_items:
    - python-minimal
    - python-pip
    - python3-pip
    - python3-venv

- import_role: 
    name: ./python/pyenv
  vars:
    pyenv_global: "{{ python_global_version }} system"
    pyenv_python_versions: '{{pyenv_global_versions}}'