
- name: Check if exa tmp directory exists
  stat:
    path: /usr/local/bin/exa
  register: tmp_exa

- name: Create exa tmp directory
  file:
    path: /tmp/exa
    state: directory
  when: tmp_exa.stat.exists == false

- name: Download rust install file
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/exa/rust_install.sh
    mode: u+rwx
    checksum: sha256:{{ rust_checksum }}
  when: tmp_exa.stat.exists == false

- name: Update repositories cache
  apt:
    update_cache: yes
  when: tmp_exa.stat.exists == false

- name: Ensure curl is present
  become: yes
  package: name=curl state=present
  when: tmp_exa.stat.exists == false

- name: Ensure unzip is present
  become: yes
  package: name=unzip state=present
  when: tmp_exa.stat.exists == false

- name: Run rust install
  command: /tmp/exa/rust_install.sh -y -q
  when: tmp_exa.stat.exists == false

- name: Download exa binary and move it to /usr/local/bin/exa
  become: yes
  unarchive:
    src: https://github.com/ogham/exa/releases/download/v0.8.0/exa-linux-x86_64-0.8.0.zip
    dest: /usr/local/bin/
    remote_src: yes
  when: tmp_exa.stat.exists == false

- name: Move exa binary to /usr/local/bin/exa
  become: yes
  command: mv /usr/local/bin/exa-linux-x86_64 /usr/local/bin/exa
  when: tmp_exa.stat.exists == false

- name: Verify exa command works
  command: exa
  when: tmp_exa.stat.exists == false