
- name: Install the gpg key for nodejs LTS
  become: yes
  become_method: sudo 
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: yes
  become_method: sudo 
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_lsb.codename }} main"
    state: present
    update_cache: yes

- name: Install the nodejs
  become: yes
  become_method: sudo 
  apt:
    name: nodejs
    state: present