---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Check if docker executable is found
      shell: docker --version
    - name: Check if docker-compose executable is found
      shell: docker-compose --version
